const sequelize=require('../database/db');
const {DataTypes}=require('sequelize')
const loansTaken=sequelize.define('loansTaken',{
    id:{
        type:DataTypes.INTEGER,
        autoIncrement:true,
        allowNull:false,
        primaryKey:true
    },
    loanType:{
        type:DataTypes.TEXT,
        allowNull:true
    },
    duration:{
        type:DataTypes.STRING,
        allowNull:true
    },
    amount:{
        type:DataTypes.INTEGER,
        allowNull:true
    },
    phone:{
        type:DataTypes.STRING(11),
        allowNull:true
    },
    bank:{
        type:DataTypes.STRING(40),
        allowNull:true,
    },
    account:{
        type:DataTypes.STRING(10),
        allowNull:true
    },
    picture:{
        type:DataTypes.STRING,
        allowNull:true
    },
    email:{
        type:DataTypes.STRING(35),
        allowNull:false
    },
    bvn:{
        type:DataTypes.INTEGER(14),
        allowNull:true
    },
    name:{
        type:DataTypes.STRING(50),
        allowNull:false
    },
    returned:{
        type:DataTypes.STRING(10),
        allowNull:false
    }
})

module.exports=loansTaken;