const sequelize=require('../database/db');
const {DataTypes}=require('sequelize');
const users=sequelize.define("users",{
    id:{
        type:DataTypes.INTEGER,
        primaryKey:true,
        autoIncrement:true,
        allowNull:false,
    },
    email:{
        type:DataTypes.STRING(35),
        unique:true,
        allowNull:false
    },
    bvn:{
        type:DataTypes.INTEGER(14),
        allowNull:true,
        unique:true
    },
    name:{
        type:DataTypes.STRING(50),
        allowNull:true
    },
    password:{
        type:DataTypes.STRING,
        allowNull:false
    },
    phone:{
        type:DataTypes.STRING(11),
        allowNull:true
    },
    bank:{
        type:DataTypes.STRING(40),
        allowNull:true,
    },
    account:{
        type:DataTypes.INTEGER(10),
        allowNull:true
    },
    picture:{
        type:DataTypes.STRING,
        allowNull:true
    },
    appointmentLetter:{
        type:DataTypes.STRING,
        allowNull:true
    },
    salary:{
        type:DataTypes.INTEGER,
        allowNull:true
    },
    otp:{
        type:DataTypes.INTEGER(6),
        allowNull:false
    },
    address:{
        type:DataTypes.STRING(150),
        allowNull:true
    }

})

module.exports=users
